name: Plugin asset/readme update

on:
  push:
    branches:
      - trunk
    paths:
      - 'readme.txt'
      - '.wordpress-org/**'
  workflow_dispatch:

concurrency:
  group: assets-deploy
  cancel-in-progress: true

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: WordPress.org plugin asset/readme update
        uses: 10up/action-wordpress-plugin-asset-update@2.2.0
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: ${{ github.event.repository.name }}
          IGNORE_OTHER_FILES: true
